apiVersion: v1
kind: Service
metadata:
  name: detyrekursi-svc1
spec:
  selector:
    app: detyrekursi
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: detyrekursi-svc1
spec:
  selector:
    app: detyrekursi
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8080
  type: NodePort

# kubectl apply -f app-service.yaml 